'------------------------------------------------------------------------------
' <auto-generated>
'     Este código lo generó una herramienta.
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se regenera el código. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Manage

    ''' <summary>
    ''' Control SuccessMessagePlaceHolder.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents SuccessMessagePlaceHolder As Global.System.Web.UI.WebControls.PlaceHolder

    ''' <summary>
    ''' Control ChangePassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents ChangePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Control CreatePassword.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents CreatePassword As Global.System.Web.UI.WebControls.HyperLink

    ''' <summary>
    ''' Control PhoneNumber.
    ''' </summary>
    ''' <remarks>
    ''' Campo generado automáticamente.
    ''' Para modificarlo, mueva la declaración del campo del archivo del diseñador al archivo de código subyacente.
    ''' </remarks>
    Protected WithEvents PhoneNumber As Global.System.Web.UI.WebControls.Label
    
End Class
